export const HANDL_ID_PLAIN="HANDL_ID_PLAIN";
export const HANDL_DE_PLAIN="HANDL_DE_PLAIN";
export const HANDL_A_PLAIN="HANDL_A_PLAIN";
export const HANDL_SUJET_PALIN="HANDL_SUJET_PALIN";
export const HANDL_REPONSE_PALIN="HANDL_REPONSE_PALIN";
export const HANDL_COMMENT_PLAIN="const HANDL_COMMENT_PLAIN";
export const HANDL_ALL_PLAINTES="HANDL_ALL_PLAINTES";





